[deps]
BenchCommon = "76005f04-6934-4268-acce-645816235ed3"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MajoranaPropagation = "c1ba0b60-2606-4ffc-8aea-7c4a0f2726e4"
PauliPropagation = "293282d5-3c99-4fb6-92d0-fd3280a19750"

[compat]
BenchCommon = "=0.1.0"
BenchmarkTools = "=1.8.0"
JSON3 = "=1.14.3"
MajoranaPropagation = "=0.3.0"
PauliPropagation = "=0.7.3"
julia = "=1.11.3"

[sources]
BenchCommon = {path = "../propaq-benchmarks/julia/BenchCommon"}
MajoranaPropagation = {url = "https://github.com/SparqleSim/MajoranaPropagation.jl", rev = "b7849cb4bac5b604f0d2fe6ff807ed889305e668"}
PauliPropagation = {url = "https://github.com/SparqleSim/PauliPropagation.jl", rev = "v0.7.3"}
