[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "propaq-benchmarks"
version = "0.1.0"
description = "Utilities to set up and run propaq benchmarks"
requires-python = ">=3.11"
dependencies = [
    "numpy==2.3.0",
    "qiskit==2.4.2",
]

[tool.setuptools.packages.find]
where = ["src"]
